//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace worktimecalc2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int s_LenOfWorkDayH {
            get {
                return ((int)(this["s_LenOfWorkDayH"]));
            }
            set {
                this["s_LenOfWorkDayH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int s_LenOfWorkDayM {
            get {
                return ((int)(this["s_LenOfWorkDayM"]));
            }
            set {
                this["s_LenOfWorkDayM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 12pt")]
        public global::System.Drawing.Font s_rtfFont {
            get {
                return ((global::System.Drawing.Font)(this["s_rtfFont"]));
            }
            set {
                this["s_rtfFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas, 12pt")]
        public global::System.Drawing.Font s_lvFont {
            get {
                return ((global::System.Drawing.Font)(this["s_lvFont"]));
            }
            set {
                this["s_lvFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string s_LastText {
            get {
                return ((string)(this["s_LastText"]));
            }
            set {
                this["s_LastText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_LastStyleFlopped {
            get {
                return ((bool)(this["s_LastStyleFlopped"]));
            }
            set {
                this["s_LastStyleFlopped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string s_UserName {
            get {
                return ((string)(this["s_UserName"]));
            }
            set {
                this["s_UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_forceUserName {
            get {
                return ((bool)(this["s_forceUserName"]));
            }
            set {
                this["s_forceUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool s_ShowDiagram {
            get {
                return ((bool)(this["s_ShowDiagram"]));
            }
            set {
                this["s_ShowDiagram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_HideOFFDAYS {
            get {
                return ((bool)(this["s_HideOFFDAYS"]));
            }
            set {
                this["s_HideOFFDAYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Hétf.|Kedd|Szerda|Csütörtök|Péntek|Szombat|Vasárnap) (\\d{4}-\\d{2}-\\d{2}) true")]
        public string s_Regex_DaysOff {
            get {
                return ((string)(this["s_Regex_DaysOff"]));
            }
            set {
                this["s_Regex_DaysOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Hétf.|Kedd|Szerda|Csütörtök|Péntek|Szombat|Vasárnap) (\\d{4}-\\d{2}-\\d{2}) 1")]
        public string s_Regex_VacSic {
            get {
                return ((string)(this["s_Regex_VacSic"]));
            }
            set {
                this["s_Regex_VacSic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Hétf.|Kedd|Szerda|Csütörtök|Péntek|Szombat|Vasárnap) (\\d{4}-\\d{2}-\\d{2}) (\\d{2}:" +
            "\\d{2}) - (\\d{2}:\\d{2})")]
        public string s_Regex_Proper {
            get {
                return ((string)(this["s_Regex_Proper"]));
            }
            set {
                this["s_Regex_Proper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Hétf.|Kedd|Szerda|Csütörtök|Péntek|Szombat|Vasárnap) (\\d{4}-\\d{2}-\\d{2}) 8")]
        public string s_Regex_Nothing {
            get {
                return ((string)(this["s_Regex_Nothing"]));
            }
            set {
                this["s_Regex_Nothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int s_UseLine {
            get {
                return ((int)(this["s_UseLine"]));
            }
            set {
                this["s_UseLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool s_LockView {
            get {
                return ((bool)(this["s_LockView"]));
            }
            set {
                this["s_LockView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hétfo,kedd,szerda,csütörtök,péntek,szombat,vasárnap")]
        public string s_dayNames {
            get {
                return ((string)(this["s_dayNames"]));
            }
            set {
                this["s_dayNames"] = value;
            }
        }
    }
}
